### PR TITLE
[No squash] Bugfixes

### PR DESCRIPTION
**Pull request by louisroyer**
Basically this is the return of #21, but now there are crafts for toolboxes and wifi chests work as before.
Please, let me know if something doesn't work correctly as I have not tested all changes yet.

### CODE REVIEW

**Comment by SmallJoker** [comment]
@Megaf

**Comment by Megaf** [comment]
@SmallJoker Thanks for the ping,

**Comment by Megaf** [comment]
@louisroyer will test it now

**Comment by Megaf** [comment]
@louisroyer Doesn't seem to load, it works on it own, but when I enable pipeworks neither of the mods will load.

**Comment by Megaf** [comment]
@louisroyer Ok, I tested here, seems good but wifi chest isnt taking items from the pipes.
pipes do connect to to the wifi chest but the item is not going to it.

**Comment by louisroyer** [comment]
> @louisroyer Ok, I tested here, seems good but wifi chest isnt taking items from the pipes.
> pipes do connect to to the wifi chest but the item is not going to it.

This is strange, can you describe how you tested exactly? It works on my side:

https://user-images.githubusercontent.com/55180044/110213278-9c2c9780-7e9f-11eb-8c04-6d2faf662b90.mp4

**Comment by Megaf** [comment]
@louisroyer I simply plugged a vacuum tube into the wifi chest and dropped an item close to it. The item got stuck inside the tube without ever getting inside the wifi chest.

**Comment by louisroyer** [comment]
Doesn't seems to work on master either… I will check what's missing.

**Comment by louisroyer** [comment]
Ok, it is because vacuum doesn't set owner for `can_insert` and `insert_object` (item is on ground and doesn't have owner anymore) and we need the player name to know in which wifi-chest we have to send the item. Maybe we could add an owner metadata on wifi-chest when placed and use this value for injections of items without owners?

**Comment by Megaf** [comment]
@louisroyer I don't like that solution a lot, in my opinion only the person who placed the wifi chest should be able to interact with it.
Perhaps that should be left the way it is.

I don't see an elegant way of attaching any pipe to the wifi chest really. Or we do it as you suggested.

**Review by Megaf — APPROVED** [review]

**Comment by Megaf** [comment]
> Ok, it is because vacuum doesn't set owner for `can_insert` and `insert_object` (item is on ground and doesn't have owner anymore) and we need the player name to know in which wifi-chest we have to send the item. Maybe we could send items without owners to the player who placed the wifi-chest?

@louisroyer I'm happy with the changes and ready to merge.

**Pull request merged**
