### PR TITLE
Update formspecs to look more like default chest

### PR DESCRIPTION
**Pull request by xisd**
I just noticed this mod and it looks great !
This is just a small update of the inventories formspecs based on the one from the default chest

### CODE REVIEW

**Comment by sofar** [comment]
screenshot? :)

**Comment by xisd** [comment]
> screenshot? :)

I just tried to upload one but all I get is _"Something went really wrong, and we can’t process that file."_  with png and jpg file...
There is much to see anyways, formspec from chests that do not have an additionnal button or field look exactly the same as the one from default:chest other are almost the same but with slight changes in alignment.

On an unrelated note, I was looking at the wiki about the gold key introduced in default, doesn't this make the shared chest obsolete?

**Comment by sofar** [comment]
Correct, it does make them obsolete.

**Comment by sofar** [comment]
:+1: irregardless :)

**Comment by sofar** [comment]
The background is still transparent, while the default formspecs for chest are not transparent. Maybe you can fix that as well?

**Pull request merged**
