### PR TITLE
shift+click support and new textures

### PR DESCRIPTION
**Pull request by JurajVajda**

### CODE REVIEW

**Comment by Megaf** [comment]
@JurajVajda @amadin 
I'm so sorry, I saw the PR only today. Can you please confirm that the PR is ok?
I have been extremely busy lately searching for a new place to live and will be moving tomorrow.

**Comment by sofar** [comment]
This pull request is a disaster.

**Comment by sofar** [comment]
Merged. But not with pleasure.

Please, the next time, don't ever make commits like this. It took me an HOUR to fix this up.

- separate PR's for every commit
- don't combine commits. If you do a cleanup, just make a separate PR.

Alright?

**Comment by JurajVajda** [comment]
sorry about that... will do that next time

**Pull request closed without merging**
