### PR TITLE
change wifi tiles back

### PR DESCRIPTION
**Pull request by Desour**
Imo the old textures are much nicer than the new ones and suit better to its name "wifi".
The PR that added the new textures: #11

### CODE REVIEW

**Comment by DS-Minetest** [comment]
Please feedback.

**Comment by DS-Minetest** [comment]
I'll scream now. : )
@sofar

**Comment by thomasrudin** [comment]
> I'll scream now. : )

Does that help usually?

**Comment by Megaf** [comment]
@SmallJoker What you think?

**Comment by SmallJoker** [comment]
No objections. Looks good.

**Pull request merged**
